apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-imagecolorization 
  labels:
    app: inference-imagecolorization 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-imagecolorization 
  template:
    metadata:
      labels:
        app: inference-imagecolorization 
    spec:
      containers:
      - name: inference-image-colorization
        image: mp5737/inference_deeplearning:2
        ports:
            - containerPort: 5005
      volumes:
      - name: pv-1
        persistentVolumeClaim:
          claimName: pvc-demo
        # imagePullPolicy: Always
