kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-volume-claim
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo